version: '3.3'
services:
    mysql:
        container_name: mysql
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: '123'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ./database:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5
        restart: always
        ports:
            - 9090:80
        environment:
            - PMA_ARBITRARY=1

    node:
        container_name: front
        image: node:21.5.0-slim
        ports:
            - 8080:80
        volumes:
            - ./ui:/workspace
        working_dir: /workspace
        stdin_open: true
        entrypoint: 'bash -c "npm install && npm run dev"'
        tty: true

    java:
        container_name: backend
        image: gradle:jdk17
        ports:
            - 8081:80
        volumes:
            - ./system:/workspace
            - ./.gradle-dependencies:/home/gradle/.gradle
        working_dir: /workspace
        user: gradle
        entrypoint: bash -c "./gradlew && ./gradlew bootRun & ./gradlew build --continuous"
        stdin_open: true
        tty: true