version: '3.3'
services:
    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: '123'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ./database:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:5
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
